data_path: ""
debug: true
check_constraints: true

pin_supports: 
  - {x: 0.0, y: 0.0}
roller_supports:
  - {x: 400.0, y: 0.0}

# positive magnitude: up, negative magnitude: down
point_loads:
  - {
    magnitude: -150,
    location: {x: 200.000, y: 0.0000}
  }
  
material_properties:
  # All in MPa unless otherwise stated
  pin:
    E: 17000
    shear_yield: 0
    tensile_yield: 0
    shear_ultimate: 23
    tensile_ultimate: 171
    density: 6.5e-4 # g/mm^3
  member:
    E: 3917.7
    shear_yield: 0
    tensile_yield: 0
    shear_ultimate: 0
    tensile_ultimate: 31.02
    density: 1.79e-4 # g/mm^3
  
design_parameters:
  thickness: 3.2 # mm
  pin_diameter: 0.125 # mm

constraints:
  # all mm unless otherwise stated
  bridge_width: 80
  bridge_width_tol: 5
  enforce_bridge_width: true
  bridge_height: 100
  bridge_height_tol: 5
  enforce_bridge_height: true
  bridge_length: 400
  bridge_length_tol: 10
  enforce_bridge_length: true
  enforce_support_level: true